---
# tasks file for Bind setup
- name: Install Bind
  package:
        name: "{{ item }}"
        state: present
  loop:
  - bind9
  - dnsutils

- name: Change resolv.conf
  lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: nameserver "{{ ansible_facts.default_ipv4.address  }}"


- name: create zones dir
  file:
    path: /etc/bind/zones
    state: directory 
    owner: root
    group: bind
    mode: 0755

- name: Copy named conf file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644


- name: Copy named conf local file
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: 0644


- name: Copy forward file
  template:
    src: db.forward.j2
    dest: /etc/bind/zones/db.{{ domain }}
    owner: root
    group: bind
    mode: 0644


- name: Copy reverse file
  template:
    src: db.reverse.j2
    dest: /etc/bind/zones/db.{{ rev_domain }}
    owner: root
    group: bind
    mode: 0644
  notify: restart bind
